[package]
name = "artnet_reciever"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
artnet_protocol = "0.4.1"
socket2 = { version = "0.5.2", features = ["all"] }
